#!/bin/bash

git_directoy=$(pwd -P)
user=`whoami`
uid=`id -u`
gid=`id -g`

docker run -it --rm --device=/dev/kfd --device=/dev/dri\
 --name  hip-ds\
 -e USER=$user -e UID=$uid -e GID=$gid\
 -v $git_directoy:$git_directoy\
 -w $git_directoy/\
 hip-ds

